import type { MetadataRoute } from "next";

const blogSlugs = [
  "freelance-sole-proprietor-vs-company-registration",
  "freelance-ssf-vs-rmf-vs-thaiesg-comparison",
  "freelance-fixed-rate-vs-hourly-rate-comparison",
  "freelance-bank-account-comparison-2026",
  "freelance-accounting-software-comparison",
  "freelance-marketer-financial-case-study",
  "freelance-music-producer-financial-case-study",
  "freelance-video-editor-financial-case-study",
  "freelance-tutor-financial-case-study",
  "freelance-translator-financial-case-study",
  "freelance-writer-financial-case-study",
  "freelance-youtuber-financial-case-study",
  "freelance-photographer-financial-case-study",
  "freelance-designer-financial-case-study",
  "freelance-developer-financial-case-study",
  "freelance-monthly-financial-routine-template",
  "freelance-rainy-season-slow-period-survival",
  "freelance-q4-tax-optimization-guide",
  "freelance-new-year-financial-reset",
  "freelance-songkran-financial-planning",
  "freelance-year-end-income-boost-strategy",
  "freelance-mid-year-financial-review-july",
  "freelance-tax-season-checklist-march",
  "freelance-tax-common-mistakes",
  "freelance-outsource-delegate-work",
  "freelance-financial-goal-setting",
  "freelance-foreign-client-payment-guide",
  "freelance-personal-brand-social-media",
  "freelance-time-tracking-billing-hours",
  "freelance-client-red-flags-avoid",
  "freelance-tax-deduction-home-office",
  "freelance-upskill-courses-investment",
  "freelance-nda-intellectual-property-guide",
  "freelance-quarterly-tax-payment-guide",
  "freelance-savings-high-yield-account",
  "freelance-coworking-space-vs-home",
  "freelance-retainer-contract-recurring-income",
  "freelance-credit-card-business-expenses",
  "freelance-separate-personal-business-account",
  "freelance-late-payment-collection-guide",
  "freelance-e-filing-rd-guide",
  "freelance-year-end-tax-planning",
  "freelance-receipt-tax-invoice-difference",
  "freelance-build-online-portfolio",
  "freelance-project-management-tools",
  "freelance-negotiate-rate-increase",
  "freelance-burnout-work-life-balance",
  "freelance-multiple-income-streams-tax",
  "freelance-tax-calculation-2026",
  "5-tips-manage-freelance-income-expenses",
  "professional-invoice-guide",
  "legal-tax-saving-tips-freelance",
  "getting-started-freelance-finance",
  "withholding-tax-freelance-guide",
  "freelance-pricing-strategy",
  "pnd90-tax-filing-freelance",
  "emergency-fund-6-months-guide",
  "freelance-contract-template-guide",
  "health-insurance-freelance-guide",
  "find-freelance-clients-channels",
  "best-expense-tracking-apps-freelance",
  "freelance-vs-employment-comparison",
  "ai-tools-for-freelancers",
  "freelance-social-security-section-39-40-guide",
  "freelance-retirement-planning-ssf-rmf-guide",
  "freelance-register-company-sole-owner-guide",
  "freelance-vat-registration-1-8-million-guide",
  "freelance-cashflow-management-irregular-income",
  "freelance-passive-income-investment-strategies",
  "freelance-debt-management-loan-approval-tips",
  "freelance-50-tawi-tax-credit-guide",
  "freelance-scope-creep-protect-income",
  "freelance-accounting-bookkeeping-basics",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const blogEntries = blogSlugs.map((slug) => ({
    url: `https://finlance.co/blog/${slug}`,
    lastModified: new Date(),
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  return [
    { url: "https://finlance.co", lastModified: new Date(), changeFrequency: "weekly", priority: 1 },
    { url: "https://finlance.co/login", lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: "https://finlance.co/signup", lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: "https://finlance.co/blog", lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    ...blogEntries,
  ];
}
