import type { Metadata } from "next";
import Link from "next/link";
import { DollarSign } from "lucide-react";
import BlogList from "./BlogList";

export const metadata: Metadata = {
  title: "บทความการเงินสำหรับฟรีแลนซ์ | Finlance Blog",
  description: "เคล็ดลับการเงิน ภาษี และการจัดการรายรับรายจ่ายสำหรับฟรีแลนซ์ไทย อ่านบทความที่จะช่วยให้คุณจัดการเงินได้ดีขึ้น",
  alternates: {
    canonical: "/blog",
  },
  openGraph: {
    title: "บทความการเงินสำหรับฟรีแลนซ์ | Finlance Blog",
    description: "เคล็ดลับการเงิน ภาษี และการจัดการรายรับรายจ่ายสำหรับฟรีแลนซ์ไทย",
  },
};

const posts = [
  { slug: "how-to-start-freelancing-thailand", title: "เริ่มต้นเป็นฟรีแลนซ์ยังไง คู่มือฉบับสมบูรณ์ 2569", excerpt: "คู่มือเริ่มต้นเป็นฟรีแลนซ์ในไทยฉบับสมบูรณ์ ตั้งแต่หาทักษะ สร้าง Portfolio ตั้งราคา หาลูกค้า จัดการภาษี และวางแผนการเงิน", coverImage: "/blog/covers/start-freelancing.svg", date: "2026-06-12" },
  { slug: "quit-job-to-freelance-preparation", title: "ลาออกมาเป็นฟรีแลนซ์ เตรียมตัวยังไงไม่ให้เจ๊ง", excerpt: "คู่มือเตรียมตัวก่อนลาออกจากงานประจำมาเป็นฟรีแลนซ์ ครอบคลุมเรื่องเงินสำรอง ประกันสังคม ภาษี หาลูกค้า", coverImage: "/blog/covers/quit-job-freelance.svg", date: "2026-06-11" },
  { slug: "freelance-average-income-thailand-2026", title: "รายได้ฟรีแลนซ์ไทยเฉลี่ยเท่าไหร่ 2569 แยกตามสายอาชีพ", excerpt: "สำรวจรายได้เฉลี่ยของฟรีแลนซ์ไทยในปี 2569 แยกตามสายอาชีพและประสบการณ์ พร้อมวิธีเพิ่มรายได้", coverImage: "/blog/covers/average-income.svg", date: "2026-06-10" },
  { slug: "freelance-social-security-33-resignation", title: "ประกันสังคม ม.33 ลาออกมาฟรีแลนซ์ ต้องทำอะไรบ้าง", excerpt: "คู่มือจัดการประกันสังคม ม.33 เมื่อลาออก ครอบคลุมสิทธิ์ว่างงาน การสมัคร ม.39 ภายใน 6 เดือน กองทุนสำรอง", coverImage: "/blog/covers/social-security-33.svg", date: "2026-06-09" },
  { slug: "essential-skills-for-freelancing", title: "ทักษะที่ฟรีแลนซ์ต้องมี นอกจากทักษะหลัก", excerpt: "ทักษะหลักเป็นแค่ตั๋วเข้าสนาม แต่ทักษะการเงิน การตลาด สื่อสาร บริหารเวลา คือสิ่งที่ทำให้อยู่รอด", coverImage: "/blog/covers/essential-skills.svg", date: "2026-06-08" },
  { slug: "best-freelance-careers-thailand-2026", title: "10 อาชีพฟรีแลนซ์ที่เหมาะกับคนไทย 2569", excerpt: "รวม 10 อาชีพฟรีแลนซ์ที่มีความต้องการสูง พร้อมวิเคราะห์รายได้ ความยากง่าย และแนวโน้มอนาคต", coverImage: "/blog/covers/best-careers.svg", date: "2026-06-07" },
  { slug: "financial-runway-before-freelancing", title: "เตรียมเงินเท่าไหร่ก่อนลาออกมาฟรีแลนซ์ สูตรคำนวณ Runway", excerpt: "สูตรคำนวณ Financial Runway ต้องเตรียมเงินเท่าไหร่ก่อนลาออก พร้อมตัวอย่างคำนวณจริง", coverImage: "/blog/covers/financial-runway.svg", date: "2026-06-06" },
  { slug: "employee-to-freelancer-mindset-shift", title: "เปลี่ยน Mindset จากพนักงานสู่ฟรีแลนซ์", excerpt: "การเป็นฟรีแลนซ์ไม่ใช่แค่เปลี่ยนวิธีทำงาน แต่ต้องเปลี่ยนวิธีคิดทั้งหมด จากรอคำสั่งเป็นริเริ่มเอง", coverImage: "/blog/covers/mindset-shift.svg", date: "2026-06-05" },
  { slug: "freelancing-pros-cons-honest-review", title: "ข้อดีข้อเสียของการเป็นฟรีแลนซ์ ความจริงที่ไม่มีใครบอก", excerpt: "รีวิวข้อดีข้อเสียฟรีแลนซ์แบบตรงไปตรงมา ทั้งด้านดีและด้านมืดที่ไม่มีใครพูดถึง", coverImage: "/blog/covers/pros-cons.svg", date: "2026-06-04" },
  { slug: "freelance-beginner-mistakes-avoid", title: "10 ผิดพลาดที่ฟรีแลนซ์มือใหม่ทำ และวิธีหลีกเลี่ยง", excerpt: "รวม 10 ผิดพลาดที่พบบ่อยที่สุด ตั้งแต่ตั้งราคาต่ำ ไม่ทำสัญญา ไม่แยกบัญชี จนถึงลืมภาษี", coverImage: "/blog/covers/beginner-mistakes.svg", date: "2026-06-03" },
  { slug: "freelance-exit-strategy-sell-business", title: "Exit Strategy ขายธุรกิจฟรีแลนซ์ สร้างมูลค่าให้ขายได้", excerpt: "ฟรีแลนซ์ส่วนใหญ่ไม่เคยคิดเรื่อง Exit Strategy แต่การวางแผนไว้ตั้งแต่แรกทำให้ธุรกิจมีมูลค่ามากขึ้นและสามารถขายได้ในอนาคต", coverImage: "/blog/covers/exit-strategy.svg", date: "2026-06-10" },
  { slug: "freelance-build-team-first-hire", title: "จ้างคนแรกของฟรีแลนซ์ เมื่อไหร่ จ้างใคร จ้างยังไง", excerpt: "การจ้างคนแรกเป็นก้าวสำคัญที่สุดในการขยายธุรกิจฟรีแลนซ์ แต่ก็เสี่ยงที่สุดด้วย เรียนรู้ว่าเมื่อไหร่ควรจ้าง จ้างใครก่อน และจ้างอย่างไรให้ได้ผล", coverImage: "/blog/covers/first-hire.svg", date: "2026-06-09" },
  { slug: "freelance-raise-rates-without-losing-clients", title: "ขึ้นราคาค่าบริการฟรีแลนซ์โดยไม่เสียลูกค้า คู่มือปฏิบัติจริง", excerpt: "การขึ้นราคาค่าบริการเป็นเรื่องที่ฟรีแลนซ์กลัวที่สุด แต่จำเป็นต้องทำเพื่อสะท้อนคุณค่าที่เพิ่มขึ้น เรียนรู้วิธีขึ้นราคาอย่างมืออาชีพโดยไม่เสียลูกค้าดี", coverImage: "/blog/covers/raise-rates.svg", date: "2026-06-08" },
  { slug: "freelance-recurring-revenue-strategies", title: "สร้างรายได้ Recurring สำหรับฟรีแลนซ์ หยุดเริ่มใหม่ทุกเดือน", excerpt: "ฟรีแลนซ์ที่พึ่งพา project-based income ต้องหาลูกค้าใหม่ทุกเดือน Recurring Revenue แก้ปัญหานี้ด้วยการสร้างรายได้ที่คาดการณ์ได้และสม่ำเสมอ", coverImage: "/blog/covers/recurring-revenue.svg", date: "2026-06-07" },
  { slug: "freelance-productized-service-model", title: "Productized Service เปลี่ยนบริการฟรีแลนซ์เป็นสินค้าที่ขายได้ซ้ำ", excerpt: "Productized Service คือการแปลงบริการฟรีแลนซ์ให้เป็นสินค้าที่มีราคาตายตัว Scope ชัดเจน และสามารถขายซ้ำได้ เพิ่มรายได้และลดความยุ่งยากในการ Sales", coverImage: "/blog/covers/productized-service.svg", date: "2026-06-06" },
  { slug: "freelance-scaling-solo-to-agency", title: "จากฟรีแลนซ์คนเดียวสู่ Agency เมื่อไหร่ควรขยาย?", excerpt: "ฟรีแลนซ์หลายคนฝันจะขยายเป็น Agency แต่ขยายเร็วเกินไปทำให้ล้มเหลว เรียนรู้สัญญาณที่บอกว่าถึงเวลาขยาย และวิธีทำอย่างมีแผน", coverImage: "/blog/covers/scaling-agency.svg", date: "2026-06-05" },
  { slug: "freelance-delayed-gratification-investing", title: "เลื่อนความสุขวันนี้เพื่อลงทุนพรุ่งนี้ กลยุทธ์สร้างความมั่งคั่ง", excerpt: "Delayed Gratification คือความสามารถในการรอผลตอบแทนระยะยาวแทนการสนองความต้องการทันที กลยุทธ์นี้สำคัญมากสำหรับฟรีแลนซ์ที่ต้องการสร้างความมั่งคั่ง", coverImage: "/blog/covers/delayed-gratification.svg", date: "2026-06-04" },
  { slug: "freelance-money-guilt-charging-worth", title: "เลิกรู้สึกผิดที่เก็บค่าบริการแพง คู่มือ Pricing Mindset", excerpt: "ฟรีแลนซ์หลายคนรู้สึกผิดเมื่อตั้งราคาสูง ทั้งที่ทักษะและคุณค่าที่ส่งมอบสมเหตุสมผล เรียนรู้วิธีเปลี่ยน Pricing Mindset และเก็บค่าบริการที่คุ้มค่าจริงๆ", coverImage: "/blog/covers/money-guilt.svg", date: "2026-06-03" },
  { slug: "freelance-lifestyle-inflation-trap", title: "กับดัก Lifestyle Inflation ฟรีแลนซ์รายได้เพิ่มแต่เงินเก็บไม่เพิ่ม", excerpt: "รายได้เพิ่มทุกปีแต่เงินเก็บยังเท่าเดิม นี่คือกับดัก Lifestyle Inflation ที่ฟรีแลนซ์ส่วนใหญ่ตกหลุม เรียนรู้วิธีรับมือและสร้างเงินเก็บจริงๆ", coverImage: "/blog/covers/lifestyle-inflation.svg", date: "2026-06-02" },
  { slug: "freelance-saying-no-to-bad-clients", title: "กล้าปฏิเสธลูกค้าที่ไม่ใช่ ทำไมการพูด No ช่วยให้รวยขึ้น", excerpt: "ฟรีแลนซ์หลายคนรับงานทุกอย่างเพราะกลัวไม่มีงาน แต่ความจริงคือการปฏิเสธลูกค้าที่ไม่เหมาะช่วยให้รายได้และความสุขเพิ่มขึ้น", coverImage: "/blog/covers/saying-no.svg", date: "2026-06-01" },
  { slug: "freelance-financial-anxiety-management", title: "จัดการความวิตกกังวลเรื่องเงิน คู่มือสุขภาพจิตการเงินฟรีแลนซ์", excerpt: "ความวิตกกังวลเรื่องเงินเป็นปัญหาที่ฟรีแลนซ์เผชิญบ่อยมาก เรียนรู้วิธีจัดการ Financial Anxiety อย่างเป็นระบบ ทั้งด้านจิตใจและการเงิน", coverImage: "/blog/covers/financial-anxiety.svg", date: "2026-05-31" },
  { slug: "freelance-money-mindset-scarcity-vs-abundance", title: "Mindset เงินฟรีแลนซ์: จากความขาดแคลนสู่ความมั่งคั่ง", excerpt: "Mindset เรื่องเงินส่งผลโดยตรงต่อรายได้และความสำเร็จของฟรีแลนซ์ เรียนรู้วิธีเปลี่ยนจาก Scarcity Mindset สู่ Abundance Mindset และเริ่มสร้างความมั่งคั่งจริงๆ", coverImage: "/blog/covers/money-mindset.svg", date: "2026-05-30" },
  { slug: "freelance-business-expense-categories-deep-dive", title: "เจาะลึกหมวดค่าใช้จ่ายธุรกิจ อะไรหักภาษีได้บ้าง", excerpt: "ฟรีแลนซ์หักภาษีได้จากค่าใช้จ่ายธุรกิจจริงหรือเหมา เจาะลึกทุกหมวดค่าใช้จ่าย อะไรหักได้ อะไรหักไม่ได้ พร้อมเคล็ดลับเก็บเอกสารให้ถูกต้อง", coverImage: "/blog/covers/business-expense-categories.svg", date: "2026-05-29" },
  { slug: "freelance-retirement-calculation-deep-dive", title: "เจาะลึกคำนวณเงินเกษียณ ฟรีแลนซ์ต้องเก็บเดือนละเท่าไหร่", excerpt: "ฟรีแลนซ์ไม่มีกองทุนสำรองเลี้ยงชีพจากนายจ้าง ต้องวางแผนเกษียณเอง เจาะลึกสูตรคำนวณเงินเกษียณ ว่าต้องเก็บเดือนละเท่าไหร่ขึ้นอยู่กับอายุและเป้าหมาย", coverImage: "/blog/covers/retirement-calculation.svg", date: "2026-05-28" },
  { slug: "freelance-insurance-types-deep-dive", title: "เจาะลึกประกันภัยทุกประเภทที่ฟรีแลนซ์ควรมี", excerpt: "ฟรีแลนซ์ไม่มีสวัสดิการจากนายจ้าง ต้องซื้อประกันเอง เจาะลึกทุกประเภทประกัน ประกันสุขภาพ อุบัติเหตุ ชีวิต และประกันวิชาชีพ พร้อมคำแนะนำจัดพอร์ต", coverImage: "/blog/covers/insurance-types.svg", date: "2026-05-27" },
  { slug: "freelance-invoice-payment-terms-deep-dive", title: "เจาะลึก Payment Terms และ Invoice ฟรีแลนซ์ตั้งเงื่อนไขจ่ายเงินยังไง", excerpt: "Payment Terms ที่ดีช่วยให้ฟรีแลนซ์ได้เงินเร็วขึ้นและลดความเสี่ยงไม่ได้รับเงิน เจาะลึกทุกรูปแบบ NET 15, NET 30, มัดจำล่วงหน้า พร้อมตัวอย่างจริง", coverImage: "/blog/covers/invoice-payment-terms.svg", date: "2026-05-26" },
  { slug: "freelance-copyright-work-for-hire-deep-dive", title: "เจาะลึกลิขสิทธิ์และ Work for Hire ฟรีแลนซ์เป็นเจ้าของผลงานจริงไหม?", excerpt: "ฟรีแลนซ์ไทยส่วนใหญ่ไม่รู้ว่าตัวเองเป็นเจ้าของลิขสิทธิ์ผลงานหรือไม่ เจาะลึก Work for Hire กฎหมายลิขสิทธิ์ไทย และวิธีปกป้องผลงานของคุณ", coverImage: "/blog/covers/copyright-work-for-hire.svg", date: "2026-05-25" },
  { slug: "freelance-digital-nomad-tax-residency", title: "ภาษีสำหรับ Digital Nomad ฟรีแลนซ์ ทำงานจากไทย รับเงินจากต่างประเทศ", excerpt: "ฟรีแลนซ์ที่ทำงาน remote จากไทยให้ลูกค้าต่างประเทศ ต้องเสียภาษีที่ไหน กฎ 180 วัน สนธิสัญญาภาษีซ้อน กฎใหม่นำเงินเข้าประเทศ", coverImage: "/blog/covers/digital-nomad-tax.svg", date: "2026-05-24" },
  { slug: "freelance-social-security-benefits-deep-dive", title: "เจาะลึกสิทธิประโยชน์ประกันสังคม ม.39/40 สำหรับฟรีแลนซ์", excerpt: "เจาะลึกทุกสิทธิประโยชน์ประกันสังคม ม.39 และ ม.40 ทั้ง 3 ทางเลือก เจ็บป่วย ทุพพลภาพ ชราภาพ คลอดบุตร พร้อมวิธีสมัครและใช้สิทธิ์", coverImage: "/blog/covers/social-security-benefits.svg", date: "2026-05-23" },
  { slug: "freelance-income-tax-brackets-deep-dive", title: "เจาะลึกอัตราภาษีก้าวหน้า 2569 ฟรีแลนซ์เสียภาษีจริงเท่าไหร่", excerpt: "เข้าใจระบบภาษีก้าวหน้าให้ถูกต้อง ทำไมรายได้ 1 ล้านไม่ได้เสียภาษี 25% พร้อมตัวอย่างคำนวณ Effective Tax Rate สำหรับฟรีแลนซ์", coverImage: "/blog/covers/income-tax-brackets.svg", date: "2026-05-22" },
  { slug: "freelance-vat-system-deep-dive", title: "เจาะลึกระบบ VAT สำหรับฟรีแลนซ์ จด VAT เมื่อไหร่ ทำอะไรบ้าง", excerpt: "ทุกเรื่องที่ฟรีแลนซ์ต้องรู้เกี่ยวกับ VAT เมื่อไหร่ต้องจด ภาษีซื้อภาษีขายคืออะไร วิธียื่น ภ.พ.30 พร้อมตัวอย่างคำนวณ VAT จริง", coverImage: "/blog/covers/vat-system-freelance.svg", date: "2026-05-21" },
  { slug: "freelance-withholding-tax-3-percent-deep-dive", title: "เจาะลึกภาษีหัก ณ ที่จ่าย 3% สำหรับฟรีแลนซ์ ทุกเรื่องที่ต้องรู้", excerpt: "เจาะลึกทุกเรื่องภาษีหัก ณ ที่จ่าย 3% สำหรับฟรีแลนซ์ ใครหัก เมื่อไหร่ เอกสาร 50 ทวิ วิธีขอคืนภาษี พร้อมตัวอย่างคำนวณจริง", coverImage: "/blog/covers/withholding-tax-3-percent.svg", date: "2026-05-20" },
  { slug: "freelance-coworking-space-comparison-bangkok", title: "เปรียบเทียบ Co-working Space กรุงเทพ 2569 ที่ไหนดีสำหรับฟรีแลนซ์?", excerpt: "เปรียบเทียบ Co-working Space ในกรุงเทพฯ JustCo, HUBBA, AIS D.C., The Hive, True Digital Park ราคา สิ่งอำนวยความสะดวก ทำเลที่ตั้ง", coverImage: "/blog/covers/coworking-comparison-bangkok.svg", date: "2026-05-19" },
  { slug: "freelance-actual-vs-lump-sum-tax-deduction", title: "หักค่าใช้จ่ายจริง vs เหมา ฟรีแลนซ์เลือกแบบไหนประหยัดภาษีกว่า?", excerpt: "เปรียบเทียบการหักค่าใช้จ่ายแบบเหมาและตามจริง สำหรับรายได้ 40(2) และ 40(7)(8) พร้อมตัวอย่างคำนวณภาษีจริงทุกระดับรายได้", coverImage: "/blog/covers/actual-vs-lump-sum-deduction.svg", date: "2026-05-18" },
  { slug: "freelance-platform-comparison-2026", title: "เปรียบเทียบแพลตฟอร์มหางานฟรีแลนซ์ 2569 ที่ไหนดีสุด?", excerpt: "เปรียบเทียบ Upwork, Fiverr, Fastwork, Toptal, Freelancer.com ค่าคอม ข้อดีข้อเสีย กลยุทธ์สร้าง profile พร้อมแนะนำแพลตฟอร์มตามสายงาน", coverImage: "/blog/covers/freelance-platform-comparison.svg", date: "2026-05-17" },
  { slug: "freelance-health-insurance-vs-social-security", title: "ประกันสุขภาพเอกชน vs ประกันสังคม ฟรีแลนซ์เลือกแบบไหนคุ้มกว่า?", excerpt: "เปรียบเทียบประกันสังคม ม.39/40 กับประกันสุขภาพเอกชน เบี้ย ความคุ้มครอง สิทธิ์ลดหย่อนภาษี พร้อมกลยุทธ์ผสมที่คุ้มที่สุดสำหรับฟรีแลนซ์", coverImage: "/blog/covers/health-insurance-vs-social-security.svg", date: "2026-05-16" },
  { slug: "freelance-payment-gateway-comparison", title: "เปรียบเทียบช่องทางรับชำระเงินสำหรับฟรีแลนซ์ 2569", excerpt: "เปรียบเทียบ PromptPay, PayPal, Stripe, Wise, GB Prime Pay ค่าธรรมเนียม ข้อดีข้อเสีย พร้อมแนะนำช่องทางรับเงินที่เหมาะกับฟรีแลนซ์แต่ละประเภท", coverImage: "/blog/covers/payment-gateway-comparison.svg", date: "2026-05-15" },
  { slug: "freelance-sole-proprietor-vs-company-registration", title: "เปรียบเทียบ: บุคคลธรรมดา vs จดทะเบียนบริษัท — ฟรีแลนซ์ควรจดบริษัทเมื่อไหร่?", excerpt: "เปรียบเทียบข้อดีข้อเสียของการทำงานเป็นบุคคลธรรมดา vs จดทะเบียนบริษัท สำหรับฟรีแลนซ์ไทย พร้อมตัวอย่างคำนวณภาษีจริง", coverImage: "/blog/covers/sole-proprietor-vs-company.svg", date: "2026-05-14" },
  { slug: "freelance-ssf-vs-rmf-vs-thaiesg-comparison", title: "เปรียบเทียบ SSF vs RMF vs ThaiESG 2569 ฟรีแลนซ์ควรลงทุนกองไหนก่อน?", excerpt: "เปรียบเทียบกองทุน SSF RMF และ ThaiESG สำหรับฟรีแลนซ์ เงื่อนไข ข้อจำกัด สิทธิลดหย่อน พร้อมกลยุทธ์เลือกกองทุนตามระดับรายได้", coverImage: "/blog/covers/ssf-rmf-thaiesg.svg", date: "2026-05-13" },
  { slug: "freelance-fixed-rate-vs-hourly-rate-comparison", title: "เปรียบเทียบ: คิดเงินแบบเหมา vs รายชั่วโมง — ฟรีแลนซ์ควรเลือกแบบไหน?", excerpt: "เปรียบเทียบข้อดีข้อเสียของการคิดเงินแบบเหมาโปรเจกต์ vs รายชั่วโมง สำหรับฟรีแลนซ์ พร้อมสูตรคำนวณราคาและแนวทางเลือก", coverImage: "/blog/covers/fixed-vs-hourly.svg", date: "2026-05-12" },
  { slug: "freelance-bank-account-comparison-2026", title: "เปรียบเทียบบัญชีธนาคารสำหรับฟรีแลนซ์ 2569 เปิดบัญชีไหนดี?", excerpt: "เปรียบเทียบบัญชีธนาคารไทยสำหรับฟรีแลนซ์ กรุงไทย SCB กสิกร TTB ออมสิน ดอกเบี้ย ค่าธรรมเนียม app PromptPay พร้อมแนะนำกลยุทธ์เปิด 2 บัญชี", coverImage: "/blog/covers/bank-account-comparison.svg", date: "2026-05-11" },
  { slug: "freelance-accounting-software-comparison", title: "เปรียบเทียบซอฟต์แวร์บัญชีสำหรับฟรีแลนซ์ 2569 ใช้ตัวไหนดี?", excerpt: "เปรียบเทียบซอฟต์แวร์บัญชีสำหรับฟรีแลนซ์ไทย FlowAccount PEAK iTAX Google Sheets Wave ราคา ฟีเจอร์ ข้อดีข้อเสีย พร้อมแนะนำตัวเลือกตามสถานการณ์", coverImage: "/blog/covers/accounting-software.svg", date: "2026-05-10" },
  { slug: "freelance-marketer-financial-case-study", title: "Case Study: Digital Marketer ฟรีแลนซ์ จากทำ Social Media สู่ Growth Consultant หลักแสน", excerpt: "เส้นทางของ digital marketer ฟรีแลนซ์ จากรับทำ social media สู่ growth consultant รายได้หลักแสน", coverImage: "/blog/covers/marketer-case-study.svg", date: "2026-05-09" },
  { slug: "freelance-music-producer-financial-case-study", title: "Case Study: Music Producer ฟรีแลนซ์ สร้างรายได้จากเสียงทั้ง Active และ Passive Income", excerpt: "เส้นทางการเงินของ music producer ฟรีแลนซ์ ตั้งแต่ทำ jingle จนถึงสร้าง passive income จาก beat และ royalty", coverImage: "/blog/covers/music-producer-case-study.svg", date: "2026-05-08" },
  { slug: "freelance-video-editor-financial-case-study", title: "Case Study: Video Editor ฟรีแลนซ์ จากตัดวิดีโอคลิปละ 1,500 สู่ Post-Production Studio", excerpt: "เส้นทางการเงินของ video editor ฟรีแลนซ์ จากตัดวิดีโอ YouTube สู่ post-production studio รายได้หลักแสน", coverImage: "/blog/covers/video-editor-case-study.svg", date: "2026-05-07" },
  { slug: "freelance-tutor-financial-case-study", title: "Case Study: Tutor ฟรีแลนซ์ จากสอนชั่วโมงละ 300 สู่ Online Academy รายได้หลักแสน", excerpt: "จาก tutor สอนตัวต่อตัวชั่วโมงละ 300 บาท สู่ online academy ที่สร้างรายได้หลักแสนต่อเดือน", coverImage: "/blog/covers/tutor-case-study.svg", date: "2026-05-06" },
  { slug: "freelance-translator-financial-case-study", title: "Case Study: Translator ฟรีแลนซ์ จากแปลคำละ 1 บาทสู่ Localization Specialist หกหลัก", excerpt: "เส้นทางของ translator ฟรีแลนซ์ จากแปลทั่วไปคำละ 1 บาท สู่ localization specialist รายได้หกหลัก", coverImage: "/blog/covers/translator-case-study.svg", date: "2026-05-05" },
  { slug: "freelance-writer-financial-case-study", title: "Case Study: Writer/Copywriter ฟรีแลนซ์ จากคำละบาทสู่ Content Strategist หกหลัก", excerpt: "เรียนรู้เส้นทางจริงของ writer ฟรีแลนซ์ จากเขียนบทความคำละ 0.5 บาท สู่ content strategist รายได้หกหลัก", coverImage: "/blog/covers/writer-case-study.svg", date: "2026-05-04" },
  { slug: "freelance-youtuber-financial-case-study", title: "Case Study: YouTuber/Content Creator ฟรีแลนซ์ สร้างรายได้หลายช่องทางจากคอนเทนต์", excerpt: "เจาะลึกเส้นทางการเงินของ YouTuber และ Content Creator ฟรีแลนซ์ จัดการรายได้ 5 ช่องทาง ภาษี AdSense", coverImage: "/blog/covers/youtuber-case-study.svg", date: "2026-05-03" },
  { slug: "freelance-photographer-financial-case-study", title: "Case Study: Photographer ฟรีแลนซ์ บริหารรายได้ไม่สม่ำเสมอและลงทุนอุปกรณ์", excerpt: "วิธีบริหารรายได้ที่ขึ้นลงตามฤดูกาล การตัดสินใจลงทุนอุปกรณ์ และกลยุทธ์สร้างรายได้หลายช่องทาง", coverImage: "/blog/covers/photographer-case-study.svg", date: "2026-05-02" },
  { slug: "freelance-designer-financial-case-study", title: "Case Study: Designer ฟรีแลนซ์ จากทำโลโก้ 3,000 สู่ Brand Consultant หกหลัก", excerpt: "เส้นทางจริงของ designer ฟรีแลนซ์ ที่เริ่มจากโลโก้ราคา 3,000 บาท จนกลายเป็น brand consultant รายได้หกหลัก", coverImage: "/blog/covers/designer-case-study.svg", date: "2026-05-01" },
  { slug: "freelance-developer-financial-case-study", title: "Case Study: Developer ฟรีแลนซ์ บริหารเงินอย่างไรจาก 30K สู่ 150K/เดือน", excerpt: "เส้นทางจริงของ Developer ฟรีแลนซ์ไทย ตั้งแต่รับงานแรก 30,000 สู่รายได้ 150,000 บาทต่อเดือน", coverImage: "/blog/covers/developer-case-study.svg", date: "2026-04-30" },
  { slug: "freelance-monthly-financial-routine-template", title: "รูทีนการเงินรายเดือนสำหรับฟรีแลนซ์: Template จัดการเงินใน 85 นาที", excerpt: "Template รูทีนการเงินรายเดือนสำหรับฟรีแลนซ์ แบ่งเป็น 4 สัปดาห์ ครอบคลุมตั้งแต่สรุปรายได้ กันเงินภาษี ติดตามหนี้ ไปจนถึงทบทวนเป้าหมาย ใช้เวลาแค่ 85 นาทีต่อเดือน", coverImage: "/blog/covers/monthly-routine.svg", date: "2026-04-29" },
  { slug: "freelance-rainy-season-slow-period-survival", title: "ฟรีแลนซ์เอาตัวรอดช่วง Low Season อย่างไร: คู่มือรับมือช่วงงานน้อย", excerpt: "คู่มือเอาตัวรอดสำหรับฟรีแลนซ์ช่วง Low Season หรือฤดูฝน เตรียมตัวก่อนงานหด บริหารเงินสำรอง หารายได้เสริม", coverImage: "/blog/covers/rainy-season-survival.svg", date: "2026-04-28" },
  { slug: "freelance-q4-tax-optimization-guide", title: "วางแผนภาษี Q4 สำหรับฟรีแลนซ์: คู่มือประหยัดภาษีก่อนสิ้นปี", excerpt: "คู่มือวางแผนภาษีไตรมาส 4 ตั้งแต่ทบทวนรายได้ เลือกค่าลดหย่อน SSF RMF ThaiESG ไปจนถึงเตรียมเอกสารก่อน 31 ธันวาคม", coverImage: "/blog/covers/q4-tax-optimization.svg", date: "2026-04-27" },
  { slug: "freelance-new-year-financial-reset", title: "ปีใหม่ รีเซ็ตการเงินฟรีแลนซ์ ตั้งเป้าหมายและงบประมาณใหม่", excerpt: "เริ่มต้นปีใหม่ด้วยการรีเซ็ตการเงิน สรุปปีที่ผ่านมา ตั้งเป้าหมายใหม่ วางงบประมาณ และวางแผนภาษีล่วงหน้า", coverImage: "/blog/covers/new-year-reset.svg", date: "2026-04-24" },
  { slug: "freelance-songkran-financial-planning", title: "วางแผนการเงินช่วงสงกรานต์ ฟรีแลนซ์รับมืองานหยุดยาวอย่างไร", excerpt: "ลูกค้าหยุดยาว งานชะงัก รายได้หายไป 1-2 สัปดาห์ เรียนรู้วิธีวางแผนการเงินรับมือช่วงสงกรานต์", coverImage: "/blog/covers/songkran-planning.svg", date: "2026-04-23" },
  { slug: "freelance-year-end-income-boost-strategy", title: "กลยุทธ์เพิ่มรายได้ปลายปีสำหรับฟรีแลนซ์ก่อนปิดงบ", excerpt: "Q4 คือช่วงโอกาสทองของฟรีแลนซ์ บริษัทมีงบเหลือต้องใช้ก่อนสิ้นปี เรียนรู้ 6 กลยุทธ์เพิ่มรายได้ปลายปี", coverImage: "/blog/covers/year-end-boost.svg", date: "2026-04-22" },
  { slug: "freelance-mid-year-financial-review-july", title: "รีวิวการเงินกลางปีสำหรับฟรีแลนซ์ ทำทุกเดือนกรกฎาคม", excerpt: "ผ่านมาครึ่งปีแล้ว เป้าหมายการเงินถึงไหน? รีวิวการเงินกลางปีช่วยให้ฟรีแลนซ์ปรับแผนได้ทันก่อนสิ้นปี", coverImage: "/blog/covers/mid-year-review.svg", date: "2026-04-21" },
  { slug: "freelance-tax-season-checklist-march", title: "ฟรีแลนซ์เตรียมตัวยื่นภาษีเดือนมีนาคม เช็กลิสต์ครบทุกขั้นตอน", excerpt: "ถึงเวลายื่นภาษีประจำปีแล้ว! รวมเช็กลิสต์ครบทุกขั้นตอน ตั้งแต่เตรียมเอกสาร คำนวณภาษี ยื่น e-Filing", coverImage: "/blog/covers/tax-season-checklist.svg", date: "2026-04-20" },
  { slug: "freelance-tax-common-mistakes", title: "10 ข้อผิดพลาดภาษีที่ฟรีแลนซ์ทำบ่อย และวิธีแก้ไขก่อนโดนปรับ", excerpt: "ฟรีแลนซ์หลายคนเสียเงินโดยไม่จำเป็นเพราะข้อผิดพลาดภาษีที่ป้องกันได้ รวม 10 ข้อผิดพลาดที่พบบ่อยที่สุด พร้อมวิธีแก้ไขทีละข้อ", coverImage: "/blog/covers/tax-mistakes.svg", date: "2026-04-19" },
  { slug: "freelance-outsource-delegate-work", title: "จ้างคนช่วยงาน เมื่อไหร่ฟรีแลนซ์ควร Outsource และวิธีทำให้คุ้มค่า", excerpt: "ฟรีแลนซ์ไม่จำเป็นต้องทำทุกอย่างเอง เรียนรู้วิธีตัดสินใจว่าเมื่อไหร่ควร outsource งานไหนควรจ้าง และจะจ้างยังไงให้คุ้มค่า", coverImage: "/blog/covers/outsource.svg", date: "2026-04-18" },
  { slug: "freelance-financial-goal-setting", title: "ตั้งเป้าหมายการเงินสำหรับฟรีแลนซ์ คู่มือวางแผนการเงินทุกระยะ", excerpt: "ฟรีแลนซ์ไม่มีเงินเดือนประจำ การตั้งเป้าหมายการเงินจึงสำคัญกว่าพนักงานประจำ เรียนรู้วิธีตั้งเป้าหมายการเงินระยะสั้น กลาง ยาว พร้อมสูตรคำนวณจริง", coverImage: "/blog/covers/financial-goal.svg", date: "2026-04-17" },
  { slug: "freelance-foreign-client-payment-guide", title: "รับงานลูกค้าต่างชาติ วิธีรับเงินและจัดการภาษีฉบับสมบูรณ์", excerpt: "ฟรีแลนซ์ไทยรับงานลูกค้าต่างประเทศต้องรู้อะไรบ้าง ตั้งแต่ช่องทางรับเงิน อัตราแลกเปลี่ยน ภาษี ไปจนถึงการออกใบแจ้งหนี้เป็นสกุลเงินต่างประเทศ", coverImage: "/blog/covers/foreign-client.svg", date: "2026-04-16" },
  { slug: "freelance-personal-brand-social-media", title: "สร้าง Personal Brand บนโซเชียลมีเดีย คู่มือฟรีแลนซ์ดึงดูดลูกค้าให้มาหาเอง", excerpt: "ฟรีแลนซ์ไม่ต้องวิ่งหาลูกค้าถ้ามี Personal Brand ที่แข็งแรง เรียนรู้วิธีสร้างแบรนด์ส่วนตัวบนโซเชียลมีเดียที่ดึงดูดลูกค้าคุณภาพ", coverImage: "/blog/covers/personal-brand.svg", date: "2026-04-15" },
  { slug: "freelance-time-tracking-billing-hours", title: "Time Tracking สำหรับฟรีแลนซ์ วิธีจับเวลาและคิดค่าบริการรายชั่วโมง", excerpt: "ฟรีแลนซ์คิดค่าบริการรายชั่วโมงยังไงให้คุ้มค่า เรียนรู้วิธีจับเวลา เครื่องมือ Time Tracking และสูตรคำนวณ Hourly Rate", coverImage: "/blog/covers/time-tracking.svg", date: "2026-04-14" },
  { slug: "freelance-client-red-flags-avoid", title: "สัญญาณอันตรายจากลูกค้า 10 Red Flags ที่ฟรีแลนซ์ต้องระวัง", excerpt: "ไม่ใช่ลูกค้าทุกคนจะดี เรียนรู้ 10 สัญญาณเตือนที่บอกว่าลูกค้ารายนี้อาจทำให้คุณเสียเวลา เสียเงิน หรือเสียสุขภาพจิต", coverImage: "/blog/covers/client-red-flags.svg", date: "2026-04-13" },
  { slug: "freelance-tax-deduction-home-office", title: "ค่าใช้จ่าย Home Office หักภาษีได้ไหม? คู่มือฟรีแลนซ์ทำงานที่บ้าน", excerpt: "ฟรีแลนซ์ทำงานที่บ้าน ค่าไฟ ค่าเน็ต ค่าอุปกรณ์ หักภาษีได้ไหม? เรียนรู้วิธีหักค่าใช้จ่ายจริง vs เหมา และเอกสารที่ต้องเก็บ", coverImage: "/blog/covers/home-office-tax.svg", date: "2026-04-12" },
  { slug: "freelance-upskill-courses-investment", title: "ลงทุนพัฒนาตัวเอง คอร์สเรียนไหนคุ้มค่าสำหรับฟรีแลนซ์ 2569", excerpt: "เรียนอะไรดีถึงจะเพิ่มรายได้ได้จริง? รวมคอร์สและทักษะที่ฟรีแลนซ์ควรลงทุนเรียน พร้อมวิธีคำนวณ ROI ของการเรียน", coverImage: "/blog/covers/upskill-courses.svg", date: "2026-04-11" },
  { slug: "freelance-nda-intellectual-property-guide", title: "NDA และทรัพย์สินทางปัญญา สิ่งที่ฟรีแลนซ์ต้องรู้ก่อนเซ็นสัญญา", excerpt: "NDA คืออะไร? ลิขสิทธิ์ผลงานเป็นของใคร? เรียนรู้เรื่อง NDA และทรัพย์สินทางปัญญาที่ฟรีแลนซ์ต้องเข้าใจก่อนเซ็นสัญญา", coverImage: "/blog/covers/nda-ip.svg", date: "2026-04-10" },
  { slug: "freelance-quarterly-tax-payment-guide", title: "ภาษีครึ่งปี ภ.ง.ด.94 คู่มือยื่นภาษีกลางปีสำหรับฟรีแลนซ์", excerpt: "ฟรีแลนซ์ต้องยื่นภาษีครึ่งปี ภ.ง.ด.94 ด้วย! เรียนรู้ว่าใครต้องยื่น วิธีคำนวณ กำหนดเวลา และวิธียื่นออนไลน์", coverImage: "/blog/covers/quarterly-tax.svg", date: "2026-04-09" },
  { slug: "freelance-savings-high-yield-account", title: "บัญชีออมทรัพย์ดอกเบี้ยสูง 2569 ฟรีแลนซ์เก็บเงินที่ไหนดี", excerpt: "เปรียบเทียบบัญชีออมทรัพย์ดอกเบี้ยสูงในไทย 2569 TTB ME Save, KBank MAKE, SCB EasyApp พร้อมแนะนำกลยุทธ์ฝากเงินสำหรับฟรีแลนซ์", coverImage: "/blog/covers/savings-account.svg", date: "2026-04-08" },
  { slug: "freelance-coworking-space-vs-home", title: "Co-working Space vs ทำงานที่บ้าน เปรียบเทียบต้นทุนและประสิทธิภาพ", excerpt: "ทำงานที่บ้านหรือไป co-working space ดีกว่ากัน? เปรียบเทียบต้นทุน ประสิทธิภาพ และความเหมาะสมสำหรับฟรีแลนซ์แต่ละประเภท", coverImage: "/blog/covers/coworking.svg", date: "2026-04-07" },
  { slug: "freelance-retainer-contract-recurring-income", title: "Retainer Contract สร้างรายได้ประจำสำหรับฟรีแลนซ์", excerpt: "หยุดหาลูกค้าใหม่ทุกเดือน เรียนรู้วิธีสร้าง Retainer Contract ที่ให้รายได้สม่ำเสมอ พร้อมตัวอย่างแพ็กเกจและวิธีเสนอลูกค้า", coverImage: "/blog/covers/retainer-contract.svg", date: "2026-04-06" },
  { slug: "freelance-credit-card-business-expenses", title: "ใช้บัตรเครดิตให้เป็นประโยชน์ เคล็ดลับบัตรเครดิตสำหรับฟรีแลนซ์", excerpt: "บัตรเครดิตไม่ใช่ศัตรู ถ้าใช้เป็นจะเป็นเครื่องมือทรงพลัง เรียนรู้วิธีใช้บัตรเครดิตเป็น cash flow buffer และสะสมแต้มจากค่าใช้จ่ายธุรกิจ", coverImage: "/blog/covers/credit-card.svg", date: "2026-04-05" },
  { slug: "freelance-separate-personal-business-account", title: "แยกบัญชีส่วนตัวกับบัญชีธุรกิจ ทำไมฟรีแลนซ์ต้องแยก?", excerpt: "เงินเข้าออกปนกัน ไม่รู้กำไรจริง ยื่นภาษีลำบาก เรียนรู้วิธีแยกบัญชีส่วนตัวกับธุรกิจ พร้อมขั้นตอนปฏิบัติจริง", coverImage: "/blog/covers/separate-accounts.svg", date: "2026-04-04" },
  { slug: "freelance-late-payment-collection-guide", title: "ลูกค้าจ่ายช้า ทวงยังไงให้ได้เงิน ไม่เสียลูกค้า", excerpt: "ปัญหาลูกค้าจ่ายเงินช้าเป็นเรื่องปกติของฟรีแลนซ์ เรียนรู้วิธีทวงหนี้อย่างมืออาชีพ 4 ระดับ พร้อมตัวอย่างข้อความ", coverImage: "/blog/covers/late-payment.svg", date: "2026-04-03" },
  { slug: "freelance-e-filing-rd-guide", title: "วิธียื่นภาษีออนไลน์ e-Filing ทีละขั้นตอน สำหรับฟรีแลนซ์ 2569", excerpt: "คู่มือยื่นภาษีออนไลน์ผ่าน rd.go.th ทีละขั้นตอน ตั้งแต่สมัครสมาชิก กรอกรายได้ ค่าลดหย่อน จนถึงชำระภาษีหรือขอคืน", coverImage: "/blog/covers/e-filing.svg", date: "2026-04-02" },
  { slug: "freelance-year-end-tax-planning", title: "วางแผนภาษีก่อนสิ้นปี 10 วิธีลดภาษีถูกกฎหมายสำหรับฟรีแลนซ์", excerpt: "อย่ารอจนถึง มี.ค. ค่อยคิดเรื่องภาษี วางแผนตั้งแต่ ต.ค.-ธ.ค. ช่วยประหยัดภาษีได้หลายหมื่น", coverImage: "/blog/covers/year-end-tax.svg", date: "2026-04-01" },
  { slug: "freelance-receipt-tax-invoice-difference", title: "ใบเสร็จรับเงิน vs ใบกำกับภาษี ต่างกันยังไง ฟรีแลนซ์ใช้ตอนไหน", excerpt: "หลายคนสับสนระหว่างใบเสร็จรับเงินกับใบกำกับภาษี ทั้งสองแตกต่างกันอย่างไร เมื่อไหร่ต้องออกแบบไหน", coverImage: "/blog/covers/receipt-tax-invoice.svg", date: "2026-03-31" },
  { slug: "freelance-build-online-portfolio", title: "สร้าง Portfolio ออนไลน์ ดึงดูดลูกค้าคุณภาพสำหรับฟรีแลนซ์", excerpt: "Portfolio คือหน้าตาธุรกิจของฟรีแลนซ์ เรียนรู้วิธีสร้าง portfolio ออนไลน์ที่ดึงดูดลูกค้าคุณภาพ พร้อมโครงสร้างและตัวอย่าง", coverImage: "/blog/covers/portfolio.svg", date: "2026-03-30" },
  { slug: "freelance-project-management-tools", title: "7 เครื่องมือจัดการโปรเจกต์ ฟรีแลนซ์ต้องมี 2569", excerpt: "รีวิว 7 เครื่องมือจัดการโปรเจกต์ที่เหมาะกับฟรีแลนซ์ เปรียบเทียบฟีเจอร์ ราคา และความเหมาะสม", coverImage: "/blog/covers/project-management.svg", date: "2026-03-29" },
  { slug: "freelance-negotiate-rate-increase", title: "ขึ้นราคางานฟรีแลนซ์ เจรจายังไงไม่ให้ลูกค้าหาย", excerpt: "ทำงานมาตั้งนาน ราคายังเท่าเดิม? เรียนรู้ 5 ขั้นตอนขึ้นราคาอย่างมืออาชีพ พร้อมสคริปต์เจรจา", coverImage: "/blog/covers/negotiate-rate.svg", date: "2026-03-28" },
  { slug: "freelance-burnout-work-life-balance", title: "Burnout ฟรีแลนซ์ สัญญาณเตือน วิธีรับมือ และการสร้าง Work-Life Balance", excerpt: "ฟรีแลนซ์เป็น burnout ได้ง่ายกว่าที่คิด เรียนรู้สัญญาณเตือนและวิธีฟื้นฟู", coverImage: "/blog/covers/burnout.svg", date: "2026-03-27" },
  { slug: "freelance-multiple-income-streams-tax", title: "มีรายได้หลายทาง ฟรีแลนซ์ยื่นภาษียังไงให้ถูกต้อง", excerpt: "ฟรีแลนซ์ที่มีรายได้จากหลายทาง ต้องยื่นภาษียังไงให้ถูกต้องและไม่เสียภาษีซ้ำซ้อน", coverImage: "/blog/covers/multiple-income-tax.svg", date: "2026-03-26" },
  { slug: "freelance-accounting-bookkeeping-basics", title: "ทำบัญชีเบื้องต้นสำหรับฟรีแลนซ์ จดรายรับรายจ่ายอย่างมืออาชีพ", excerpt: "ฟรีแลนซ์ไม่จำเป็นต้องเป็นนักบัญชี แต่ควรรู้พื้นฐานการจดบันทึกรายรับรายจ่าย แยกบัญชีส่วนตัวกับธุรกิจ", coverImage: "/blog/covers/bookkeeping.svg", date: "2026-03-25" },
  { slug: "freelance-scope-creep-protect-income", title: "Scope Creep คืออะไร? วิธีป้องกันงานบานปลายที่กินกำไรฟรีแลนซ์", excerpt: "ลูกค้าขอเพิ่มงานทีละนิด จนโปรเจกต์บานปลายเกินราคาที่ตกลง เรียนรู้วิธีป้องกันและตั้งราคา change request", coverImage: "/blog/covers/scope-creep.svg", date: "2026-03-24" },
  { slug: "freelance-50-tawi-tax-credit-guide", title: "หนังสือรับรอง 50 ทวิ คืออะไร? ฟรีแลนซ์ต้องเก็บ ต้องตรวจ ต้องใช้ยังไง", excerpt: "50 ทวิ คือเอกสารสำคัญที่ฟรีแลนซ์ต้องเก็บทุกใบ เพราะเป็นกุญแจในการขอภาษีคืน", coverImage: "/blog/covers/50-tawi.svg", date: "2026-03-23" },
  { slug: "freelance-debt-management-loan-approval-tips", title: "ฟรีแลนซ์มีหนี้ จัดการยังไง? + เคล็ดลับกู้เงินให้ผ่าน", excerpt: "ไม่มีสลิปเงินเดือนแต่อยากกู้ซื้อบ้านหรือรถ? เรียนรู้วิธีเตรียมเอกสารรายได้และเทคนิคเพิ่มโอกาสอนุมัติ", coverImage: "/blog/covers/debt-management.svg", date: "2026-03-22" },
  { slug: "freelance-passive-income-investment-strategies", title: "7 วิธีสร้าง Passive Income สำหรับฟรีแลนซ์ ให้เงินทำงานแทนคุณ", excerpt: "ฟรีแลนซ์ไม่ควรพึ่งพาแค่ active income จากงานรับจ้าง เริ่มสร้าง passive income จากการลงทุน", coverImage: "/blog/covers/passive-income.svg", date: "2026-03-21" },
  { slug: "freelance-cashflow-management-irregular-income", title: "บริหารกระแสเงินสดฉบับฟรีแลนซ์ รายได้ไม่แน่นอนก็รอดได้", excerpt: "รายได้เดือนละไม่เท่ากัน เรียนรู้ระบบจัดการ cash flow แบบ bucket system สำหรับฟรีแลนซ์", coverImage: "/blog/covers/cashflow-management.svg", date: "2026-03-20" },
  { slug: "freelance-vat-registration-1-8-million-guide", title: "รายได้เกิน 1.8 ล้าน ฟรีแลนซ์ต้องจด VAT! สิ่งที่ต้องรู้ก่อนสาย", excerpt: "เมื่อรายได้เกิน 1.8 ล้านบาทต่อปี ต้องจดทะเบียน VAT ภายใน 30 วัน ไม่รู้ไม่ได้แปลว่าไม่ผิด", coverImage: "/blog/covers/vat-registration.svg", date: "2026-03-19" },
  { slug: "freelance-register-company-sole-owner-guide", title: "ฟรีแลนซ์ควรเปิดบริษัทคนเดียวเมื่อไร? คู่มือจดทะเบียนฉบับสมบูรณ์", excerpt: "รายได้เริ่มเยอะ ภาษีเริ่มหนัก เปรียบเทียบภาษีบุคคลธรรมดา vs นิติบุคคล พร้อมขั้นตอนจดทะเบียน", coverImage: "/blog/covers/register-company.svg", date: "2026-03-18" },
  { slug: "freelance-retirement-planning-ssf-rmf-guide", title: "วางแผนเกษียณสำหรับฟรีแลนซ์ SSF, RMF และทางเลือกลดหย่อนภาษี 2026", excerpt: "ฟรีแลนซ์ไม่มีกองทุนสำรองเลี้ยงชีพ ต้องวางแผนเกษียณเอง เจาะลึก SSF RMF ThaiESG", coverImage: "/blog/covers/retirement-planning.svg", date: "2026-03-17" },
  { slug: "freelance-social-security-section-39-40-guide", title: "ประกันสังคมฟรีแลนซ์ มาตรา 39 vs 40 เลือกแบบไหนคุ้มกว่า?", excerpt: "เปรียบเทียบสิทธิประโยชน์และเงินสมทบระหว่างมาตรา 39 กับ 40 พร้อมแนะนำทางเลือกที่เหมาะกับคุณ", coverImage: "/blog/covers/social-security.svg", date: "2026-03-16" },
  { slug: "withholding-tax-freelance-guide", title: "ภาษีหัก ณ ที่จ่าย ฟรีแลนซ์ คู่มือฉบับสมบูรณ์", excerpt: "ทุกเรื่องที่ฟรีแลนซ์ต้องรู้เกี่ยวกับภาษีหัก ณ ที่จ่าย ตั้งแต่อัตราการหัก วิธีจัดการ การขอคืนภาษี ไปจนถึงการอ่านหนังสือ 50 ทวิ", coverImage: "/blog/covers/withholding-tax.svg", date: "2026-03-10" },
  { slug: "freelance-pricing-strategy", title: "ตั้งราคาค่าบริการฟรีแลนซ์ คู่มือคำนวณอย่างมืออาชีพ", excerpt: "เรียนรู้ 3 วิธีตั้งราคาค่าบริการฟรีแลนซ์ พร้อมสูตรคำนวณและตัวอย่างจริง", coverImage: "/blog/covers/pricing-strategy.svg", date: "2026-03-08" },
  { slug: "pnd90-tax-filing-freelance", title: "วิธียื่นภาษี ภ.ง.ด.90 สำหรับฟรีแลนซ์ ขั้นตอนครบจบ", excerpt: "คู่มือยื่นภาษี ภ.ง.ด.90 แบบ step-by-step สำหรับฟรีแลนซ์ ตั้งแต่เอกสารที่ต้องเตรียม วิธียื่นผ่าน e-Filing ไปจนถึงโทษของการยื่นล่าช้า", coverImage: "/blog/covers/pnd90-filing.svg", date: "2026-03-06" },
  { slug: "emergency-fund-6-months-guide", title: "สร้าง Emergency Fund 6 เดือน คู่มือฟรีแลนซ์", excerpt: "ทำไมฟรีแลนซ์ต้องมีเงินสำรองฉุกเฉินมากกว่าพนักงานประจำ วิธีคำนวณ เก็บที่ไหน และกลยุทธ์สร้างให้เร็วขึ้น", coverImage: "/blog/covers/emergency-fund.svg", date: "2026-03-05" },
  { slug: "freelance-contract-template-guide", title: "สัญญาจ้างงานฟรีแลนซ์ ตัวอย่างและข้อควรระวัง", excerpt: "ทำไมฟรีแลนซ์ต้องมีสัญญาจ้างงาน องค์ประกอบสำคัญ เงื่อนไขการจ่ายเงิน ลิขสิทธิ์ พร้อมตัวอย่างจริง", coverImage: "/blog/covers/contract-guide.svg", date: "2026-03-04" },
  { slug: "health-insurance-freelance-guide", title: "ประกันสุขภาพสำหรับฟรีแลนซ์ เลือกแบบไหนดี", excerpt: "เปรียบเทียบประกันสุขภาพทุกแบบ ตั้งแต่ประกันสังคม ม.39/40 ประกันเอกชน ไปจนถึงประกันชีวิต+สุขภาพ", coverImage: "/blog/covers/health-insurance.svg", date: "2026-03-02" },
  { slug: "freelance-tax-calculation-2026", title: "วิธีคำนวณภาษีสำหรับฟรีแลนซ์ 2026", excerpt: "เรียนรู้วิธีคำนวณภาษีเงินได้บุคคลธรรมดาสำหรับฟรีแลนซ์ ตั้งแต่การหักค่าใช้จ่าย ค่าลดหย่อน ไปจนถึงอัตราภาษีก้าวหน้า", coverImage: "/blog/covers/tax-calculation.svg", date: "2026-03-01" },
  { slug: "find-freelance-clients-channels", title: "หาลูกค้าฟรีแลนซ์ 10 ช่องทางที่ได้ผลจริง", excerpt: "รวม 10 ช่องทางหาลูกค้าฟรีแลนซ์ ตั้งแต่ LinkedIn Referral ไปจนถึง Content Marketing", coverImage: "/blog/covers/find-clients.svg", date: "2026-02-28" },
  { slug: "best-expense-tracking-apps-freelance", title: "7 แอปบันทึกรายรับรายจ่าย ที่ฟรีแลนซ์ต้องมี", excerpt: "รีวิว 7 แอปบันทึกรายรับรายจ่ายที่เหมาะกับฟรีแลนซ์ไทย เปรียบเทียบฟีเจอร์ ราคา และฟังก์ชันภาษี", coverImage: "/blog/covers/expense-apps.svg", date: "2026-02-25" },
  { slug: "freelance-vs-employment-comparison", title: "ฟรีแลนซ์ vs พนักงานประจำ เปรียบเทียบครบทุกมิติ", excerpt: "เปรียบเทียบชีวิตฟรีแลนซ์กับพนักงานประจำ ตั้งแต่รายได้ สวัสดิการ ภาษี ไปจนถึง Work-Life Balance", coverImage: "/blog/covers/freelance-vs-employment.svg", date: "2026-02-22" },
  { slug: "5-tips-manage-freelance-income-expenses", title: "5 เทคนิคจัดการรายรับ-รายจ่ายฟรีแลนซ์", excerpt: "เทคนิคง่ายๆ ที่ช่วยให้ฟรีแลนซ์จัดการเงินได้อย่างเป็นระบบ ไม่ปนเงินส่วนตัวกับเงินธุรกิจ", coverImage: "/blog/covers/income-expenses.svg", date: "2026-02-20" },
  { slug: "ai-tools-for-freelancers", title: "ใช้ AI ช่วยงานฟรีแลนซ์ เครื่องมือและวิธีใช้จริง", excerpt: "รวม AI tools ที่ฟรีแลนซ์ใช้ได้จริง ตั้งแต่เขียนคอนเทนต์ ออกแบบ เขียนโค้ด ไปจนถึงจัดการเงิน", coverImage: "/blog/covers/ai-tools.svg", date: "2026-02-18" },
  { slug: "professional-invoice-guide", title: "ใบแจ้งหนี้ที่ดีควรมีอะไรบ้าง", excerpt: "สร้างใบแจ้งหนี้แบบมืออาชีพ มีข้อมูลครบถ้วน ลูกค้าจ่ายเร็วขึ้น พร้อมตัวอย่างและเทมเพลต", coverImage: "/blog/covers/invoice-guide.svg", date: "2026-02-10" },
  { slug: "legal-tax-saving-tips-freelance", title: "วิธีประหยัดภาษีถูกกฎหมายสำหรับฟรีแลนซ์", excerpt: "รวม 7 วิธีลดภาษีที่ถูกกฎหมาย ตั้งแต่ค่าลดหย่อนส่วนตัว ประกัน ไปจนถึง SSF/RMF", coverImage: "/blog/covers/tax-saving.svg", date: "2026-01-25" },
  { slug: "getting-started-freelance-finance", title: "เริ่มต้นเป็นฟรีแลนซ์ ต้องเตรียมเรื่องเงินยังไง", excerpt: "คู่มือเตรียมตัวด้านการเงินสำหรับคนที่กำลังจะเริ่มเป็นฟรีแลนซ์ ตั้งแต่กองทุนฉุกเฉิน ไปจนถึงการวางแผนภาษี", coverImage: "/blog/covers/getting-started.svg", date: "2026-01-15" },
];

export default function BlogPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <nav className="border-b border-border bg-card">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <DollarSign className="w-7 h-7 text-primary" />
            <span className="text-lg font-bold">Finlance</span>
          </Link>
          <Link href="/signup" className="bg-primary hover:bg-primary/90 text-white px-4 py-2 rounded-lg text-sm font-medium transition">
            เริ่มใช้ฟรี
          </Link>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-12">
        <h1 className="text-3xl sm:text-4xl font-bold mb-2">บทความการเงินสำหรับฟรีแลนซ์</h1>
        <p className="text-muted text-lg mb-10">เคล็ดลับ ความรู้ และวิธีจัดการเงินที่ฟรีแลนซ์ต้องรู้</p>

        <BlogList posts={posts} />
      </main>

      <footer className="border-t border-border py-8 text-center text-sm text-muted">
        <Link href="/" className="hover:text-foreground transition">← กลับหน้าหลัก</Link>
      </footer>
    </div>
  );
}
